### ISSUE TITLE
How to add body description for http request

### ISSUE THREAD

**Issue by SunilPatel2** [pgroot/express-swagger-generator#1]
/**
 * Member Adding API
 * @route POST /member/{memberID}
 * @group member - Operations about user
 * @body // is this possible to add
 * @returns {object} 200 - default response
 * @returns {Error}  default - Unexpected error
 */

**Comment by caferrari** [comment]
I'm having the same issue =/

**Comment by DGiles98** [comment]
Was this resolved?

**Comment by pgroot** [comment]
are you mean definitions ? 
if it is, please upgrade to `1.1.0`.  and define model definitions like this
```
/**
 * @typedef Point
 * @property {integer} x.required
 * @property {integer} y.required
 * @property {string} color
 */

 // Now I can use it as below:

 /**
  * Insert a point
  * @route POST /api/point
  * @param {Point.model} point.body.required - the new point
  */
```
