### ISSUE TITLE
validation fails for required model param

### ISSUE THREAD

**Issue by dantaub** [pgroot/express-swagger-generator#14]
This is a very cool package, but I am encountering a strange problem --
When I specify that a route requires a predefined Model, the validation fails (the text entry box turns red and the api call won't send). It works fine if I remove 'required' from the line:

`* @param {ReqNameJSON.model} name.body.required - username or email`
making it
`* @param {ReqNameJSON.model} name.body - username or email`

 but then it is not be a correct api specification...

please advise

```
/**
* JSON parameters require a model. This one just has "name"
* @typedef ReqNameJSON
* @property {string} name.required - name of person making request
*/
/**
* This route will respond greetings to name in json request body.
* @route POST /hello/
* @group hello - Test Demo
* @param {ReqNameJSON.model} name.body.required - username or email
* @returns {object} 200 - An object with the key 'msg'
* @returns {Error}  default - Unexpected error
* @produces application/json
* @consumes application/json
*/
api.post("/", hello.greetings);
```

**Comment by pgroot** [comment]
![20180723104010](https://user-images.githubusercontent.com/1168948/43054576-d3ae6a5e-8e64-11e8-80d7-bc5a4de8f556.png)

I tested your sample code, it is works fine.
Have you installed the latest version?

**Comment by dantaub** [comment]
Yes it is on latest npm version. Tanks for looking into it. Did you use the "try it out" button as well? The text field turns red and no network traffic happens. It appears to be a failing client-side validation. I also updated express-swaggerize-ui's internal swagger-ui dist code to their current master and it didn't help.


![screen shot 2018-07-23 at 9 47 22 am](https://user-images.githubusercontent.com/33430862/43080811-92466f22-8e5e-11e8-9a4e-b20c52bdb1d7.png)

**Comment by dantaub** [comment]
FYI I posted an issue on swagger-ui 
https://github.com/swagger-api/swagger-ui/issues/4755

**Comment by dantaub** [comment]
Apparently one of the problems is that the statement:
`* @returns {object} 200 - An object with the key 'msg'`
creates a swagger api json with an extra space after the "200" -- another is that typedef specifies a type, instead of a schema, which is what's used for request parameters.
