### ISSUE TITLE
how to upload file 

### ISSUE THREAD

**Issue by Manjukb** [pgroot/express-swagger-generator#22]
please leave an example to upload file

**Comment by Manjukb** [comment]
hey i solved it use below example 

/**
 * This hook is used upload file
 * @route POST /upload
 * @group fileUpload - upload zip file
 * @param  {file} data.formData.required - zip file
 * @returns {object} 200 - successfully parsed file
 * @returns {Error}  default - server error
 * @security Bearer
 */

**Comment by ketavchotaliya** [comment]
@Manjukb Thanks it works for me.
