### ISSUE TITLE
Enum

### ISSUE THREAD

**Issue by Yaty** [pgroot/express-swagger-generator#42]
Hello,
Is it possible to use [Enum](https://swagger.io/docs/specification/data-models/enums/) ?
Thanks

**Comment by pgroot** [comment]
usage
`@param {enum} status.query.required - Status values that need to be considered for filter - eg: available,pending`

**Comment by renamed** [comment]
Hello @pgroot thanks for your kind response.

Is it possible to achieve something similar to the following? We can select as many options as needed.

![image](https://user-images.githubusercontent.com/2809309/71917841-c7aed780-315f-11ea-9238-fb210ec965bc.png)
