### ISSUE TITLE
Definitions with no required field cause validation error

### ISSUE THREAD

**Issue by paglias** [pgroot/express-swagger-generator#53]
If you have a definition (`@typdef`) with no required field the Swagger spec file is not valid because it generates `required: null` which is not a valid value.

See https://online.swagger.io/validator/debug?url=https%3A%2F%2Fbookleg.herokuapp.com%2Fbackend%2Fspec.json

<img width="618" alt="Schermata 2019-06-13 alle 19 59 37" src="https://user-images.githubusercontent.com/589911/59456060-cb6ebb80-8e15-11e9-8ab2-f188645689da.png">

thanks!

**Comment by kamal0808** [comment]
@pgroot An empty `required` array is still not valid value
<img width="1184" alt="Screen Shot 2020-07-08 at 4 22 03 AM" src="https://user-images.githubusercontent.com/15616412/86852574-a9a43e80-c0d2-11ea-9392-e4e008fb1d18.png">
