### ISSUE TITLE
Example values not being filled out

### ISSUE THREAD

**Issue by georgeglessner** [pgroot/express-swagger-generator#77]
I am attempting to add example values to the docs, but the format of `- eg: example value` doesn't seem to be working. 

![image](https://user-images.githubusercontent.com/8864993/78918992-1bbea600-7a46-11ea-8ae3-36f3035ea305.png)

**Comment by GoygovRustam** [comment]
Try this. (two dashes). I think parser expects description and then example.

 * @property {string} name - - eg: example value

**Comment by georgeglessner** [comment]
I tried both, still getting same output. This is an example of how I have it setup

`@param {string} profDate.body.required - Profitability date - eg: "2/1/2020"`

**Comment by GoygovRustam** [comment]
> I tried both, still getting same output. This is an example of how I have it set up
> 
> 
> 
> `@param {string} profDate.body.required - Profitability date - eg: "2/1/2020"`

Please remove quotes

**Comment by georgeglessner** [comment]
Same thing 
![image](https://user-images.githubusercontent.com/8864993/79822727-ba9ca980-8346-11ea-8428-ea2e3ff6d94d.png)

**Comment by GoygovRustam** [comment]
There is actually an open issue for this. 

https://github.com/pgroot/express-swagger-generator/issues/41

I guess you’ll have to use a model if you want to have examples

**Comment by georgeglessner** [comment]
Ah I missed that, thank you. They should really update the docs to not have misleading info!
